# Form implementation generated from reading ui file 'WindowCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowCalendar(object):
    def setupUi(self, WindowCalendar):
        WindowCalendar.setObjectName("WindowCalendar")
        WindowCalendar.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        WindowCalendar.resize(336, 201)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/calendar-icon_34471.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowCalendar.setWindowIcon(icon)
        WindowCalendar.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(WindowCalendar)
        self.formLayout.setObjectName("formLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=WindowCalendar)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.calendarWidget)

        self.retranslateUi(WindowCalendar)
        QtCore.QMetaObject.connectSlotsByName(WindowCalendar)

    def retranslateUi(self, WindowCalendar):
        _translate = QtCore.QCoreApplication.translate
        WindowCalendar.setWindowTitle(_translate("WindowCalendar", "Calendario"))
