# Form implementation generated from reading ui file '.\templates\WindowCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowCalendar(object):
    def setupUi(self, WindowCalendar):
        WindowCalendar.setObjectName("WindowCalendar")
        WindowCalendar.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        WindowCalendar.resize(311, 188)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\img/calendar-icon_34471.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowCalendar.setWindowIcon(icon)
        WindowCalendar.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(WindowCalendar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=WindowCalendar)
        self.calendarWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)

        self.retranslateUi(WindowCalendar)
        QtCore.QMetaObject.connectSlotsByName(WindowCalendar)

    def retranslateUi(self, WindowCalendar):
        _translate = QtCore.QCoreApplication.translate
        WindowCalendar.setWindowTitle(_translate("WindowCalendar", "Calendario"))
